[workspace]
channels = ["https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo_swarm"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
op_practice = "poe op_practice"

[dependencies]
python = ">=3.10,<3.13"
modular = ">=25.5.0.dev2025062805,<26"
ipykernel = ">=6.29.5,<7"
numpy = ">=2.3.0,<3"
matplotlib = ">=3.10.3,<4"
poethepoet = ">=0.33.1,<0.34"


[tool.poe.tasks]

op_practice = [
    { cmd = "mojo package op_practice -o op_practice/op_practice.mojopkg" },
    { cmd = "python conv_1d.py" }
]